namespace Wolfgang.Etl.SqlBulkCopy.Tests.Fuzz;

/// <summary>
/// A mappable record shape with a spread of column kinds (value type, reference
/// type, nullable value type, bool) used by the fuzz properties. Field values
/// are generated by CsCheck; the type itself is fixed because CsCheck cannot
/// generate .NET types dynamically.
/// </summary>
public sealed class FuzzRecord
{
    public int A { get; set; }

    public string B { get; set; } = string.Empty;

    public int? C { get; set; }

    public bool D { get; set; }
}
